### PR TITLE
Squeaky wheels

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tcr3dr** [comment]
This branch still packs into ./wheelhouse on my computer (OS X 10.10):

```
Successfully built Flask Werkzeug Jinja2 itsdangerous MarkupSafe
a .
a ./.gitignore
a ./requirements.txt
a ./server.py
a ./wheelhouse
a ./wheelhouse/Flask-0.10.1-py2-none-any.whl
a ./wheelhouse/itsdangerous-0.24-py2-none-any.whl
a ./wheelhouse/Jinja2-2.8-py2.py3-none-any.whl
a ./wheelhouse/MarkupSafe-0.23-py2-none-any.whl
a ./wheelhouse/Werkzeug-0.11.3-py2.py3-none-any.whl
```

**Comment by peterbarker** [comment]
This branch works for me now.  Working on MacOSX, @tcr3dr?

**Comment by hamishwillee** [comment]
or @mrpollo Can one of you test this on Mac?

**Comment by hamishwillee** [comment]
Also, we really need to automate that virtualenv dependency - can you do that either in this or a separate patch?

**Comment by hamishwillee** [comment]
@peterbarker This fails on mac with same error as previously on Linux. I am 99% sure I killed the old version and installed the new one, based on `pip list`. Log below.

Arguably we should still merge if this works for Linux, because at least then it will work on 1 platform :-)

ALSO of note:
1. I had to manually install virtualenv on the mac. This did not happen automagically.
2. Before connecting to solo via solo-cli for the first time I had to SSH in (at least once). Is that a "requirement" (we have "connecting to Solo" as a requirement but we don't explicitly say that you actually have to have SSH'd in - the implication is that just connecting to Solo network might be enough)

```
Jennys-iMac:helloworld hamishwillee$ solo script pack
checking Internet connectivity...
/Library/Python/2.7/site-packages/solo_cli-1.1.1-py2.7.egg/soloutils/solocode-pack.sh: line 12: virtualenv: command not found
Jennys-iMac:helloworld hamishwillee$ sudo pip install virtualenv
The directory '/Users/hamishwillee/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/hamishwillee/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting virtualenv
  Downloading virtualenv-14.0.6-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 146kB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-14.0.6
Jennys-iMac:helloworld hamishwillee$ solo script pack
checking Internet connectivity...
New python executable in /private/tmp/solo-script/env/bin/python
Installing setuptools, pip, wheel...done.
Requirement already satisfied (use --upgrade to upgrade): wheel in ./env/lib/python2.7/site-packages
/private/tmp/solo-script/env/lib/python2.7/site-packages/pip/commands/wheel.py:126: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting dronekit>=2.0.0 (from -r ./requirements.txt (line 1))
  Downloading dronekit-2.0.2.tar.gz
Collecting pymavlink>=1.1.62 (from dronekit>=2.0.0->-r ./requirements.txt (line 1))
  Downloading pymavlink-1.1.70.tar.gz (1.8MB)
    100% |████████████████████████████████| 1.8MB 191kB/s 
Collecting requests<=2.99999,>=2.5.0 (from dronekit>=2.0.0->-r ./requirements.txt (line 1))
  Downloading requests-2.9.1.tar.gz (484kB)
    100% |████████████████████████████████| 487kB 686kB/s 
Building wheels for collected packages: dronekit, pymavlink, requests
  Running setup.py bdist_wheel for dronekit ... done
  Stored in directory: /private/tmp/solo-script/wheelhouse
  Running setup.py bdist_wheel for pymavlink ... done
  Stored in directory: /private/tmp/solo-script/wheelhouse
  Running setup.py bdist_wheel for requests ... done
  Stored in directory: /private/tmp/solo-script/wheelhouse
Successfully built dronekit pymavlink requests
a .
a ./.gitignore
a ./helloworld.py
a ./README.md
a ./requirements.txt
a ./soloscriptpack.log
a ./wheelhouse
a ./wheelhouse/dronekit-2.0.2-py2-none-py27.whl
a ./wheelhouse/pymavlink-1.1.70-py2-none-py27.whl
a ./wheelhouse/requests-2.9.1-py2.py3-none-py27.whl
Jennys-iMac:helloworld hamishwillee$ solo script run helloworld.py
connecting to solo...
checking pip...
uploading script bundle...
./
./.gitignore
./helloworld.py
./README.md
./requirements.txt
./soloscriptpack.log
./wheelhouse/
./wheelhouse/dronekit-2.0.2-py2-none-py27.whl
./wheelhouse/pymavlink-1.1.70-py2-none-py27.whl
./wheelhouse/requests-2.9.1-py2.py3-none-py27.whl
Not deleting env/bin
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
cp: can't stat '/usr/lib/python2.7/site-packages/greenlet*': No such file or directory
Ignoring indexes: https://pypi.python.org/simple
dronekit-2.0.2-py2-none-py27.whl is not a supported wheel on this platform.
running script...

Traceback (most recent call last):
  File "/log/solo-script/helloworld.py", line 1, in <module>
    from dronekit import connect
ImportError: No module named dronekit
```

**Comment by hamishwillee** [comment]
@peterbarker This works on mac! Well done. There are a few oddities in the build log, but these probably count as separate issues.

**Comment by alexblack** [comment]
I believe I'm using the latest solo-cli (installed yesterday), and still facing this issue:

```
(ddc) Alexs-MacBook-Air:solo alex$ solo script run hello_solo.py
connecting to solo...
checking pip...
script bundle already up to date.
running script...

Traceback (most recent call last):
  File "/log/solo-script/hello_solo.py", line 1, in <module>
    from dronekit import connect
ImportError: No module named dronekit
```

```
(ddc) Alexs-MacBook-Air:solo alex$ solo script run hello_solo.py
connecting to solo...
checking pip...
script bundle already up to date.
running script...

Traceback (most recent call last):
  File "/log/solo-script/hello_solo.py", line 1, in <module>
    from dronekit import connect
ImportError: No module named dronekit
(ddc) Alexs-MacBook-Air:solo alex$ solo info
connecting to Solo and the Controller...
{
  "controller": {
    "ref": "3dr-controller-imx6solo-3dr-artoo-20160304215337",
    "version": "2.1.0"
  },
  "gimbal": {
    "connected": false
  },
  "pixhawk": {
    "apm_ref": "73e08529",
    "px4firmware_ref": "5e693274",
    "px4nuttx_ref": "d48fa307",
    "version": "1.2.23"
  },
  "solo": {
    "ref": "3dr-solo-imx6solo-3dr-1080p-20160304215558",
    "version": "2.1.0"
  }
}
```

**Pull request merged**
