### PR TITLE
enabled solo-cli to flash pixhawk firmware from local drive

### PR DESCRIPTION
**Pull request by ethliup**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Awesome! @liamstask can we get this in the fast track in terms of review and interaction? Thanks!

**Comment by tcr3dr** [comment]
Hi @liupeidong88,

Can you change this to just be:

```
solo flash pixhawk <filename>
```

Since it's not an optional argument, we can just require the path/version/etc. as part of the arguments.

Otherwise, LGTM and I'll merge when the changes are made. Thanks!

**Comment by liamstask** [comment]
thanks for the PR @liupeidong88! i think it would be better to update the pixhawk without rebooting the system, which should be possible. i created #30 with a quick sketch of the shell commands that should be required.

any chance you could update this PR (or submit a new one) to use that approach?

**Comment by ethliup** [comment]
@liamstask  and @tcr3dr, I modified the command line and used loadPixhawk.py to flash pixhawk as requested. Please check them! If there is anything wrong, let me know.

**Comment by tcr3dr** [comment]
lgtm

**Comment by liamstask** [comment]
@liupeidong88, @tcr3dr - does this work? concerned that there's no management of the system runlevel before updating.

**Comment by tcr3dr** [comment]
@liamstask I'm unsure. Are you saying that the runlevel changes are not implemented from your branch? @liupeidong88

**Comment by liamstask** [comment]
i don't have a branch relevant to this PR, just saying that i do not see where in this PR that the runlevel is modified, to account for the firmware update.

**Comment by liupeidong88** [comment]
@tcr3dr @liamstask  I did not manage the run level. I tested it again in the afternoon. I found it would be more stable to reboot it after uploading the firmware instead of using loadPixhawk.py. However, sometimes the flash process will be stuck at "waiting for boot loader..." in the px4_uploader.py. I need to manually reboot it again and it then works. 

Probably I can manage the run-level as you said. I am new to this and will check it tomorrow.

**Comment by liupeidong88** [comment]
@liamstask @tcr3dr Probably you could also give some advices on this to me.

**Comment by ethliup** [comment]
@tcr3dr @liamstask I have fixed the run level management, sorry for it. Could you possible help test it again? It is evening in my place, or I can test it tomorrow. 

Previously, I reboot it after uploading the firmware. Sometimes the flash procedure would be stuck at "waiting for boot loader." from px4_uploader.py. However, it works fine after I manually reboot it. I am unsure whether it is caused by the run-level management.

**Comment by ethliup** [comment]
@tcr3dr @liamstask I tested it again. I found it would be stable if we could manually reboot it after uploading the firmware file with solo flash... I tried it several times with 2 firmware file, one is from 3-dr and another is our own, it never failed if I manually reboot it after uploading.

**Pull request merged**
