### PR TITLE
Video acquire startup

### PR DESCRIPTION
**Pull request by djnugent**
Prevents seg faults. Seg faults may occur while calling `sync`. This PR helps the issue but does not completely solve memory corruption

### CODE REVIEW

**Comment by djnugent** [comment]
Can this be pulled temporarily?  It is not ideal but it's better than having to modify video_send.sh

**Comment by djnugent** [comment]
ping

**Comment by tcr3dr** [comment]
@djnugent sure

**Comment by djnugent** [comment]
It just crossed my mind that this may break capability for people running previous versions of solo-cli. Will verify here in a minute. My bad for not thinking of that earlier.

**Comment by djnugent** [comment]
It does. I'll push a fix.

**Pull request merged**
